name: olx
description: olx Clone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.5
  animated_text_kit: ^4.2.2
  get: ^4.6.5
  flutter_signin_button: ^2.0.0
  firebase_core: ^1.19.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: 'Edu SA Beginner'
      fonts:
        - asset: assets/fonts/EduSABeginner-Bold.ttf
          weight: 700

        - asset: assets/fonts/EduSABeginner-Medium.ttf
          weight: 500

        - asset: assets/fonts/EduSABeginner-Regular.ttf
          weight: 400

        - asset: assets/fonts/EduSABeginner-SemiBold.ttf
          weight: 600
